### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by edsu** [DocNow/dnflow#14]
I was attempting to collect 50k tweets and my ec2 micro instance fell over. When I was able to log in I noticed that redis had died because it didn't have enough memory to write its snapshot. This then caused the rq workers to fail because they couldn't talk to redis.

**Comment by dchud** [comment]
Not to question whether this is a legitimate problem (it is!), but two points to consider:  maybe we need to determine or at least decide on some minimal machine requirements, and maybe we need to look into redis configuration options.

**Comment by edsu** [comment]
As we've dsiscused previously we eventually want to be able to process the Ferguson dataset. So minimally we want to be able to process millions of tweets. Obviously this prototype isn't there yet, and is really bound by how much can be collected  via a search in a a few hours tops.  Tens of thousands of tweets is a good ballpark.
