### ISSUE TITLE
/job insecure

### ISSUE THREAD

**Issue by edsu** [DocNow/dnflow#24]
Right now anyone can POST to /job and update the database. If we are going to continue along this path of having Luigi tasks update the app database using the webapp then we'll need to figure out a way to make it secure.

**Comment by dchud** [comment]
@edsu should we close this?

**Comment by edsu** [comment]
Isn't it still a problem?

**Comment by dchud** [comment]
Sure, if ensuring the prototype is secure is a priority.

**Comment by edsu** [comment]
I'd be happy with closing this if we could articulate some options for how we would do the same operation of updating the app database from the luigi tasks more securely.

**Comment by edsu** [comment]
Actually on second thought I will close this issue since we never planned for the dnflow prototype to be secure. It was meant as a thought piece to explore the design space.

The design idea that this little problem surfaced is that there will be situations where we want to communicate between workflow tasks and the app database. I see three options available, maybe there are more:
1. talk to the database directly
2. use an API call to the webapp with some authentication
3. put the message into a queue and let something else pick it up and update the database

When it comes to putting together the pieces we want in DocNow I'd like to remember this point.

**Comment by dchud** [comment]
👍
