### ISSUE TITLE
filter search list

### ISSUE THREAD

**Issue by edsu** [DocNow/dnflow#38]
Bergis and a few other people expected to only see their own searches. We were thinking this should be the default behavior. But perhaps it could be a configuration option, depending on the preference of the person running it?

**Comment by ianmilligan1** [comment]
I think a config option would be really helpful – I found it useful to be able to monitor what's going on, at least from an administrative perspective? But agreed that maybe beyond the admin user it's not necessary.

**Comment by edsu** [comment]
Yeah, I personally liked seeing the homepage as a High-Scores-esque screen where I could see what other people were doing. But I guess that's a barrier to some people and not completely appropriate in this context. We're eventually talking about adding the ability to publish and/or share datasets. I think it should be fairly easy to make it a config option if it would be useful in the AHA workshop for people to see what the group is doing.

![highscores-2-5](https://cloud.githubusercontent.com/assets/33829/20021826/0c04bf88-a2ae-11e6-8e9a-703ea5650876.gif)
